import Head from "next/head";
import dynamic from "next/dynamic";
import { useTranslation } from "react-i18next";

const Partners = dynamic(() => import("../components/Home/Partners"));
const Contact = dynamic(() => import("../components/Home/Contact"));
const Showcase = dynamic(() => import("../components/Home/Showcase"));
const Programs = dynamic(() => import("../components/Home/Programs"));
const News = dynamic(() => import("../components/Home/News"));
const Informationcard = dynamic(() => import("../components/Informationcard"));
import i18next from "i18next";
export default function Home() {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Amity Tashkent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Showcase />
      <Programs />
      <News />
      <Informationcard />
      <Partners />
      <Contact />
    </>
  );
}
